### ISSUE TITLE
Grafana doesn't show metrics 

### ISSUE THREAD

**Issue by avivzam** [paregupt/mds_traffic_monitor#1]
Hii,
I made  all the install processes step by step .
In addition there is connection between MDS to Grafana.
The script succeed, but didn't created the new files.

Thanks
Aviv

**Comment by paregupt** [comment]
Can you please check and share the logs from /var/logs/telegraf/mds_traffic_monitor*?

**Comment by avivzam** [comment]
Hii,
I see all the metrics were collected from the MDS on logs from mds_traffic_monitor

But the logs from "/var/logs/telegraf/telegraf.log" there is some error " traceback most recent call last"

**Comment by paregupt** [comment]
Can you please share the content of the logfile. That will tell us the problem.

**Comment by avivzam** [comment]
"[inputs.exec]  error in plugin: exec command time out for command python3 /usr/local/telegraf/mds_traffic_monitor_high_frequency.py /usr/local/telegraf/mds_group_1.txt influxdb-lp -vv  traceback most recent call last"

**Comment by paregupt** [comment]
Please share the output from logfile under /var/logs/telegraf/mds_traffic_monitor* directory.

**Comment by paregupt** [comment]
Did it work?

**Comment by paregupt** [comment]
Closing it. Reach out if you still need help. Thanks!
